config/routes.rb
Rails.application.routes.draw do
  resources :restaurants, only: %i[index show new create] do
    resources :reviews, only: %i[index show create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  CATEGORIES = %w[chinese italian japanese french belgian].freeze

  has_many :reviews, dependent: :destroy
  validates_presence_of :name, :address
  validates :category, inclusion: CATEGORIES

  def average_rating
    reviews.average('rating').to_f.round(1)
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates_presence_of :content
  validates :rating, numericality: { only_integer: true, in: (0..5) }

  def self.max_review_rating
    # get max value from validors[:options] :in validator
    # [#<ActiveRecord::Validations::NumericalityValidator:0x00007fcc3887c268 @attributes=[:rating], @options={:only_integer=>true, :in=>0..5}>]
    validators_on(:rating).select.first.options[:in].last
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show]

  def index
    @restaurants = Restaurant.all
  end

  def show
    @review = Review.new()
  end

  def new
    @restaurant = Restaurant.new()
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: %i[index show new create]

  def index
    @reviews = @restaurant.reviews
  end

  def show
    @review = Review.find(params[:id])
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant), alert: 'Review submitted sucessfully'
    else
      render 'restaurants/show', status: :unprocessable_entity
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def int_to_stars(int, total)
    # a => quotient - whole stars
    # b => remainder - part stars
    a, b = int.divmod(1)
    c = total - (a + b).ceil
    # FA icons
    star_filled = '<i class="fa-solid fa-star star"></i>'
    star_half = '<i class="fa-solid fa-star-half-stroke star"></i>'
    star_empty = '<i class="fa-regular fa-star star"></i>'
    # html output
    html_result = []
    # add filled stars
    a.times do
      html_result << star_filled
    end
    # add half star if needed
    html_result << star_half unless b.nil? || b.zero?
    # add empty stars
    c.times do
      html_result << star_empty
    end
    html_result.join.html_safe
  end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%# bootstrap %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%# font awesome %>
    <script src="https://kit.fontawesome.com/a86c93a2cb.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<nav class="navbar bg-dark sticky-top px-3">
  <h1 class="text-light">All Restaurants</h1>
  <%= link_to "Add new restaurant",
              new_restaurant_path,
              class: "btn btn-primary"
              %>
</nav>
<div class="container cards">
  <div class="row row-cols-1 row-cols-md-2 g-4">
    <% @restaurants.each do |restaurant| %>
      <%= render "shared/restaurant/card", restaurant: restaurant%>
    <% end %>
  </div>
</div>

app/views/restaurants/new.html.erb
<div class="container">
  <div class="mb-3">
    <h1>Add new restaurant</h1>
    <%= link_to "Back to Restaurants", restaurants_path, class: "link-unstyled" %>
  </div>
  <%= render :partial => "shared/restaurant/form" %>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <div>
    <%= render "shared/restaurant/restaurant_profile" %>
  </div>
  <div class="mb-3 narrow-form">
    <%= render "shared/review/form" %>
  </div>
  <div class="container">
    <h2>All reviews (<%= "#{@restaurant.reviews.count}" %>)</h2>
    <%= render "shared/restaurant/review_display" %>
  </div>
</div>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/index.html.erb
<div class="container">
  <div class="border-bottom">
    <%= render "shared/restaurant/restaurant_profile" %>
  </div>
  <div class="container">
    <%= render "shared/restaurant/review_display" %>
  </div>
</div>

app/views/reviews/new.html.erb
<h1>Add review for <%= @restaurant.name %></h1>
<%= render :partial => "shared/review/form" %>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

app/views/shared/restaurant/_card.html.erb
<div class="col">
  <div class="card m-3">
    <%= image_tag "https://source.unsplash.com/random/297x180?sig=#{rand(1..100)}", alt: "unsplash", width: 300, height: 200, class: "card-img-top" %>
    <div class="card-body bg-light justify-content-between d-flex">
      <h5 class="card-title">
        <%= link_to restaurant.name, restaurant_path(restaurant), class: "link-unstyled text-success" %>
      </h5>
      <p class="card-text">
        <%= restaurant.category.capitalize %>
      </p>
    </div>
    <div class="card-footer justify-content-between d-flex">
      <small class="text-muted">
        Average rating: <%= int_to_stars(restaurant.average_rating, Review.max_review_rating) %>
      </small>
      <small class="text-muted">
        <%= link_to "See all #{restaurant.reviews.count} review(s)", restaurant_reviews_path(restaurant) %>
      </small>
    </div>
  </div>
</div>

app/views/shared/restaurant/_form.html.erb
<div class="container">
  <%= simple_form_for @restaurant do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.input :category, collection: %w[chinese italian japanese french belgian] %>
    <%= f.submit "Add restaurant", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/shared/restaurant/_restaurant_profile.html.erb
<div class="container d-flex m-3">
  <div class="card">
    <img src=<%= "https://source.unsplash.com/random/150x150?sig=#{rand(1..100)}" %> class="restaurant-profile-img card-img-top" alt="">
    <%= link_to "Back to Restaurants", restaurants_path, class: "link-unstyled card-footer" %>
  </div>
  <div class="ms-5 dflex">
    <div class="row">
      <h1><%= @restaurant.name %></h1>
      <h3><%= int_to_stars(@restaurant.average_rating, Review.max_review_rating) %> (<%= @restaurant.reviews.count %>)<h3>
    </div>
    <h3 class="row"><%= @restaurant.address %> | <%= @restaurant.phone_number %></h3>
  </div>
</div>

app/views/shared/restaurant/_review_display.html.erb
<% @restaurant.reviews.each do |review| %>
  <div class="border-bottom d-flex">
    <p class="me-3">
      <%= int_to_stars(review.rating, Review.max_review_rating) %>
    </p>
    <p class="row">
      <%= review.content %>
    </p>
  </div>
<% end %>

app/views/shared/review/_form.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content, :label => "What did you think of #{@restaurant.name}?" %>
  <%= f.input :rating, collection: 0..5 %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>